var dataset = [
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia, Singapore",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history.",
        "New Naratif LLC",
        "Non-profit",
        "English, Bahasa Indonesia, Tagalog",
        "00 64 129829829, info@newnaratif.com",     
        "2014",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Seed",
        "Fers",
        "$100,000",
        "Shares",
        "23 Jul 2000",
        "Funding, Partners, Mentors, Training",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "Old Naratif",
        "Community",
        "Singapore",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "Bahasa Indonesia, Tagalog",
        "00 64 129829829, info@newnaratif.com",     
        "2011",
        "PJ Thum",
        "20",
        "Bootstrapping",
        "Founders",
        "$10,000",
        "Shares",
        "1 Jun 2011",
        "Training, Partners",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "My Naratif",
        "Editorial tools",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "English, Bahasa Indonesia",
        "info@newnaratif.com",     
        "2010",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Seed",
        "Founders",
        "$1,000",
        "Shares",
        "1 Jan 2019",
        "Mentors",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Editorial tools, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "English",
        "00 64 129829829, info@newnaratif.com",     
        "2008",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Series A",
        "Founders",
        "$200,000",
        "Shares",
        "9 Nov 2012",
        "Funding, Mentors",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Editorial tools",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "Bahasa Indonesia",
        "00 64 129829829, info@newnaratif.com",     
        "2009",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Series B",
        "Founders",
        "$1,100,000",
        "Shares",
        "5 Dec 2011",
        "Training, Mentors",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Analytics, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Private Limited",
        "Mandarin, English",
        "00 64 129829829, info@newnaratif.com",     
        "2013",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Bootstrapping",
        "Founders",
        "$2,100,000",
        "Shares",
        "12 May 2012",
        "Partners",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Analytics",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "Mandarin",
        "00 64 129829829, info@newnaratif.com",     
        "2010",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Seed",
        "Founders",
        "$150,000",
        "Shares",
        "14 Aug 1995",
        "Funding, Partners",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "Hindi, English",
        "00 64 129829829, info@newnaratif.com",     
        "2015",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Series C",
        "Founders",
        "$120,000",
        "Shares",
        "1 Jan 2015",
        "Funding, Mentors",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "Thai, English",
        "00 64 129829829, info@newnaratif.com",     
        "2017",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Series A",
        "Founders",
        "$100,000",
        "Shares",
        "2 Jan 2011",
        "Mentors, Partners",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "Thai",
        "00 64 129829829, info@newnaratif.com",     
        "2018",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Series B",
        "Founders",
        "$600,000",
        "Shares",
        "2 Apr 2011",
        "Training, Mentors",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "Bengali",
        "00 64 129829829, info@newnaratif.com",     
        "2019",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Seed",
        "Founders",
        "$100,000",
        "Shares",
        "11 Oct 2010",
        "Training, Partners",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "Burmese",
        "00 64 129829829, info@newnaratif.com",     
        "2010",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Bootstrapping",
        "Founders",
        "$800,000",
        "Shares",
        "1 Jan 2019",
        "Partners, Mentors",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Private Limited",
        "Malay, Mandarin",
        "00 64 129829829, info@newnaratif.com",     
        "2005",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Series A",
        "Founders",
        "$900,000",
        "Shares",
        "1 Jan 2019",
        "Funding, Mentors",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "Malay",
        "00 64 129829829, info@newnaratif.com",     
        "2001",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Series A",
        "Founders",
        "$100,000",
        "Shares",
        "1 Jan 2019",
        "Funding",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "English, Bengali",
        "00 64 129829829, info@newnaratif.com",     
        "2010",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Seed",
        "Founders",
        "$1,200,000",
        "Shares",
        "1 Jan 2019",
        "Mentors",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "English, Burmese",
        "00 64 129829829, info@newnaratif.com",     
        "1999",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Series A",
        "Founders",
        "$300,000",
        "Shares",
        "1 Jan 2019",
        "Training",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Private Limited",
        "Khmer",
        "00 64 129829829, info@newnaratif.com",     
        "1998",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Seed",
        "Founders",
        "$125,000",
        "Shares",
        "1 Jan 2019",
        "Partners",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "English, Burmese, Khmer",
        "00 64 129829829, info@newnaratif.com",     
        "1995",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Bootstrapping",
        "Founders",
        "$100,000",
        "Shares",
        "1 Jan 2019",
        "Mentors",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "Vietnamese, Mandarin",
        "00 64 129829829, info@newnaratif.com",     
        "2003",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Series B",
        "Founders",
        "$15,000",
        "Shares",
        "1 Jan 2019",
        "Funding, Mentors",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Private Limited",
        "English, Vietnamese",
        "00 64 129829829, info@newnaratif.com",     
        "2005",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Seed",
        "Founders",
        "$20,000",
        "Shares",
        "2 Jan 2019",
        "Funding, Training",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Non-profit",
        "Vietnamese",
        "00 64 129829829, info@newnaratif.com",     
        "2009",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Seed",
        "Founders",
        "$100,000",
        "Shares",
        "1 Feb 2019",
        "Training, Partners",
    ],
    [
        "<img src='https://images.squarespace-cdn.com/content/5bff654ea9e0283ff2ea8d2b/1544290886790-3HIBTIEU1FF6KCNYAVKS/Screenshot+2018-12-06+at+7.21.05+PM.png' style='height:auto; width:200px'>",  
        "New Naratif",
        "Content publisher, Community",
        "Kuala Lumpur-Malaysia",
        "New Naratif is a movement for democracy, freedom of information, and freedom of expression in Southeast Asia. We aim to make Southeast Asians proud of our region, our shared culture, and our shared history. We fight for the dignity and freedom of the Southeast Asian people by building a community of people across the region to imagine and articulate a better Southeast Asia.",
        "New Naratif LLC",
        "Private Limited",
        "Thai, Vietnamese",
        "00 64 129829829, info@newnaratif.com",     
        "2017",
        "PJ Thum, Kirsten Han, Aisyah Llewellyn",
        "20",
        "Series C",
        "Founders",
        "$22,000",
        "Shares",
        "1 Jan 2010",
        "Funding, Partners",
    ]
];